global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'my-monitoring-stack'

rule_files:
  - 'alert.rules'
  - 'record.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'fastApi'
    static_configs:
    - targets: ['backend:5000']
    metrics_path: /api/metrics/
    scheme: http
