{
 "title": "fastApi",
 "description": "fastApi的玩意",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Запросы статус 200",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(http_requests_total{instance=~\".+\",status=\"2xx\"}[10m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "+- Время отклика за минуту",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idelta(http_request_duration_seconds_sum{job=\"fastApi\",handler!=\"none\"}[1m])/idelta(http_request_duration_seconds_count{job=\"fastApi\",handler!=\"none\"}[1m])",
     "legendFormat": "{{instance}} {{handler}}"
    }
   ]
  },
  {
   "title": "Запросы с ошибками",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(http_requests_total{handler!=\"none\",status!=\"2xx\"}[10m])",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "python_gc_objects_collected",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "abs(idelta(python_gc_objects_collected_total{job=\"fastApi\"}[1h]))",
     "legendFormat": "generation{{generation}}"
    }
   ]
  },
  {
   "title": "python_gc_collections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "abs(idelta(python_gc_collections_total{job=\"fastApi\"}[1h]))",
     "legendFormat": "generation{{generation}}"
    }
   ]
  },
  {
   "title": "python_gc_objects_uncollectable",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "abs(idelta(python_gc_objects_uncollectable_total{job=\"fastApi\"}[1h]))",
     "legendFormat": "generation{{generation}}"
    }
   ]
  }
 ]
}